definitions:
  gift.CreateRequest:
    properties:
      code:
        type: string
      codePrefix:
        type: string
      expirationDate:
        type: string
      giftAmount:
        type: integer
      startDateTime:
        type: string
      usageLimit:
        type: integer
    type: object
  gift.DTO:
    properties:
      code:
        type: string
      createdAt:
        type: string
      expirationDate:
        type: string
      giftAmount:
        type: integer
      id:
        type: integer
      startDateTime:
        type: string
      updatedAt:
        type: string
      usageLimit:
        type: integer
      usedCount:
        type: integer
    type: object
  handler.Error:
    properties:
      code:
        $ref: '#/definitions/serr.ErrorCode'
      message:
        type: string
      trace_id:
        type: string
    type: object
  serr.ErrorCode:
    enum:
    - INTERNAL
    - INVALID_GIFT_ID
    - INVALID_GIFT_CODE
    - INVALID_DISCOUNT_ID
    - INVALID_DISCOUNT_CODE
    - PERMISSION
    - GIFT_USAGE_LIMIT_REACHED
    type: string
    x-enum-varnames:
    - ErrInternal
    - ErrInvalidGiftID
    - ErrInvalidGiftCode
    - ErrInvalidDiscountID
    - ErrInvalidDiscountCode
    - ErrPermission
    - ErrGiftUsageLimitReached
info:
  contact: {}
paths:
  /gift:
    post:
      consumes:
      - application/json
      description: Initialize a new gift.
      parameters:
      - description: Gift init request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/gift.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gift.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Initialize gift
      tags:
      - GiftDTO
  /gift/{giftCode}:
    get:
      consumes:
      - application/json
      description: Get a gift by code.
      parameters:
      - description: Gift code
        in: path
        name: giftCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gift.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get gift
      tags:
      - GiftDTO
  /gift/use/{giftCode}:
    post:
      consumes:
      - application/json
      description: Use a gift code.
      parameters:
      - description: Gift code
        in: path
        name: giftCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gift.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Use gift
      tags:
      - GiftDTO
  /health:
    get:
      consumes:
      - application/json
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health check
      tags:
      - Health
swagger: "2.0"
